In [1]:
!which python

/home/rstudio/.virtualenvs/r-reticulate/bin/python


In [2]:
if 0:
    !pip install ws3 rasterio pandas scipy fiona geopandas profilehooks matplotlib

In [3]:
%load_ext autoreload
%autoreload 2

In [4]:
import spadesws3
import numpy as np
import rasterio


In [5]:
if 0:
    !pip uninstall -y ws3
    !pip install -e ./ws3

In [6]:
import ws3
print(ws3.__file__)

/workspaces/spades_ws3/ws3/ws3/__init__.py


In [7]:
model_name='tsa24_clipped' 
model_path='examples/data/woodstock_model_files'
base_year=2020
horizon=3
period_length=1
shp_path='examples/data/shp/tsa24_clipped/stands.shp'
tif_path='data'
theme_cols=['theme0', 'theme1', 'theme2', 'theme3', 'theme4']
#hdt_func = ws3.common.hash_dt

In [8]:
!rm data/*.tif

rm: cannot remove 'data/*.tif': No such file or directory


In [9]:
tif_filename = 'inventory_init.tif'
spadesws3.import_inventory(shp_path, tif_path, tif_filename, theme_cols)
spadesws3.hdtk_decode

{49742: ('tsa24_clipped', '1', '2401002', '204', '2401002'),
 54691: ('tsa24_clipped', '1', '2402002', '204', '2402002'),
 30909: ('tsa24_clipped', '0', '2401000', '100', '2401000'),
 15257: ('tsa24_clipped', '1', '2401002', '204', '2421002'),
 37496: ('tsa24_clipped', '1', '2403002', '204', '2423002'),
 34881: ('tsa24_clipped', '1', '2403002', '204', '2403002'),
 57565: ('tsa24_clipped', '1', '2403000', '100', '2403000'),
 60524: ('tsa24_clipped', '1', '2402000', '100', '2402000'),
 39700: ('tsa24_clipped', '0', '2402005', '1201', '2402005')}

In [10]:
!rm data/inventory_2*.tif; rm data/projected*.tif
!cp data/inventory_init.tif data/inventory_2020.tif

rm: cannot remove 'data/inventory_2*.tif': No such file or directory
rm: cannot remove 'data/projected*.tif': No such file or directory


In [11]:
spadesws3.add_raster_action(1, 'harvest')
spadesws3.action_decode

{1: 'harvest'}

In [12]:
with rasterio.open('data/inventory_2020.tif', 'r+') as src:
    data = src.read()
    print(data[0].sum(), data[1].sum())
    data[3][data[2] == 2] = 1 # should signal request to apply 'harvest' action to 8 pixels
    src.write(data)

64110137 136049


In [13]:
with rasterio.open('data/inventory_2020.tif', 'r') as src:
    data = src.read()
np.unique(data[3])


array([-1,  1], dtype=int32)

In [14]:
spadesws3.bootstrap_forestmodel(model_name=model_name, 
                                model_path=model_path, 
                                base_year=base_year, 
                                tif_path=tif_path,
                                tif_filename='inventory_2020.tif')
spadesws3.forestmodel
fm = spadesws3.forestmodel

In [15]:
fm.forestraster._src.read()

array([[[   -1,    -1,    -1, ...,    -1,    -1,    -1],
        [54691, 30909,    -1, ..., 30909, 49742,    -1],
        [54691, 30909,    -1, ..., 49742, 49742,    -1],
        ...,
        [15257, 15257,    -1, ..., 37496, 37496,    -1],
        [15257, 15257, 15257, ..., 37496, 37496,    -1],
        [15257, 15257, 15257, ..., 37496, 37496,    -1]],

       [[   -1,    -1,    -1, ...,    -1,    -1,    -1],
        [   95,   145,    -1, ...,   145,    78,    -1],
        [   95,   145,    -1, ...,    78,    78,    -1],
        ...,
        [    0,     0,    -1, ...,     9,     9,    -1],
        [    0,     0,     0, ...,     9,     9,    -1],
        [    0,     0,     0, ...,     9,     9,    -1]],

       [[   -1,    -1,    -1, ...,    -1,    -1,    -1],
        [  177,   178,    -1, ...,   150,   140,    -1],
        [  177,   178,    -1, ...,   140,   140,    -1],
        ...,
        [    2,     2,    -1, ...,    44,    44,    -1],
        [    2,     2,     2, ...,    44,    

In [ ]:
spadesws3.hdtk_decode[1897841230]

('tsa24_clipped', '1', '2401002', '204', '2401002')

In [ ]:
spadesws3.hdtk_decode[1631665049]

AttributeError: module 'spadesws3' has no attribute 'hdtk_decode'

In [15]:
d = spadesws3.__d
ic = spadesws3.__ic
ick = spadesws3.__ick
ickg = spadesws3.__ickg

AttributeError: module 'spadesws3' has no attribute '__d'

In [115]:
d[1][ic][ick][ickg]

array([135, 135, 135, 135, 135, 135, 135, 135])

In [116]:
d[1][ic][ick][ickg] =

SyntaxError: invalid syntax (437341648.py, line 1)

In [107]:
d[1] = 0

In [108]:
d[1]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [76]:
136049 - 113620

22429

In [25]:
fm.inventory(0)

1365.0

In [26]:
fm.inventory(1, age=135)

132.0

In [50]:
spadesws3.forestmodel.actions

{'harvest': <ws3.forest.Action at 0x7fa8651dc310>}

In [78]:
fm.inventory(1)

1459.0

In [17]:
src = rasterio.open('data/inventory_2020.tif')
data = src.read()
data[0]

array([[        -1,         -1,         -1, ...,         -1,         -1,
                -1],
       [3102201251,  685013181,         -1, ...,  685013181, 1897841230,
                -1],
       [3102201251,  685013181,         -1, ..., 1897841230, 1897841230,
                -1],
       ...,
       [1897841230, 1897841230,         -1, ..., 3499266680, 3499266680,
                -1],
       [1897841230, 1897841230, 1897841230, ..., 3499266680, 3499266680,
                -1],
       [1897841230, 1897841230, 1897841230, ..., 3499266680, 3499266680,
                -1]])

In [29]:
fm.dtypes

{}

In [18]:
for i in range(horizon):
    tif_filename='inventory_%i.tif' % (base_year+i)
    print('\n' + tif_filename)
    fm = spadesws3.bootstrap_forestmodel(model_name=model_name, 
                                         model_path=model_path, 
                                         base_year=(base_year+i), 
                                         tif_path=tif_path,
                                         tif_filename=tif_filename)
    fm.areaselector.operate(1, 'harvest', 100.)
    fm.forestraster.allocate_schedule()


inventory_2020.tif

inventory_2021.tif

inventory_2022.tif


In [54]:
dtk = ('tsa24_clipped', '1', '2402002', '204', '2402002')
age = 95

In [55]:
fm.apply_action(dtk, 'harvest', 1, 95, 0.)

(0, 0.0, [[('tsa24_clipped', '1', '2402002', '204', '2422002'), 1.0, 0]])

In [56]:
fm.hash_dt

AttributeError: 'ForestModel' object has no attribute 'hash_dt'

In [57]:
fm.dtypes

{('tsa24_clipped',
  '1',
  '2401002',
  '204',
  '2401002'): <ws3.forest.DevelopmentType at 0x7f87a7084be0>,
 ('tsa24_clipped',
  '1',
  '2402002',
  '204',
  '2402002'): <ws3.forest.DevelopmentType at 0x7f87a61560e0>,
 ('tsa24_clipped',
  '0',
  '2401000',
  '100',
  '2401000'): <ws3.forest.DevelopmentType at 0x7f87a6155f90>,
 ('tsa24_clipped',
  '1',
  '2401002',
  '204',
  '2421002'): <ws3.forest.DevelopmentType at 0x7f87a61560b0>,
 ('tsa24_clipped',
  '1',
  '2403002',
  '204',
  '2423002'): <ws3.forest.DevelopmentType at 0x7f87a6156170>,
 ('tsa24_clipped',
  '1',
  '2403002',
  '204',
  '2403002'): <ws3.forest.DevelopmentType at 0x7f87a6156260>,
 ('tsa24_clipped',
  '0',
  '2402005',
  '1201',
  '2402005'): <ws3.forest.DevelopmentType at 0x7f87a6156290>,
 ('tsa24_clipped',
  '1',
  '2402002',
  '204',
  '2422002'): <ws3.forest.DevelopmentType at 0x7f87a61561d0>}

In [58]:
src = rasterio.open('data/inventory_2020.tif')
ages = src.read(2)
ages

array([[ -1,  -1,  -1, ...,  -1,  -1,  -1],
       [ 95, 145,  -1, ..., 145,  78,  -1],
       [ 95, 145,  -1, ...,  78,  78,  -1],
       ...,
       [135, 135,  -1, ...,   9,   9,  -1],
       [135, 135, 135, ...,   9,   9,  -1],
       [135, 135, 135, ...,   9,   9,  -1]])

In [59]:
src = rasterio.open('data/inventory_2021.tif')
ages = src.read(4)
ages

array([[-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1],
       ...,
       [-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1]])

In [16]:
dt = fm.dtypes[('tsa24_clipped',
                '1',
                '2401002',
                '204',
                '2401002')]
dt._areas

KeyError: ('tsa24_clipped', '1', '2401002', '204', '2401002')

In [22]:
src.profile

NameError: name 'src' is not defined

In [78]:
src.profile['transform']

Affine(100.0, 0.0, 1112000.0,
       0.0, -100.0, 1124900.0)

In [80]:
theme_cols = ['theme0', 'theme1', 'theme2', 'theme3', 'theme4']
fm = spadesws3.bootstrap_forestmodel(model_name='tsa24_clipped', 
                                     model_path='examples/data/woodstock_model_files',
                                     base_year=2020, 
                                     tif_path='data',
                                     tif_filename='inventory_2020.tif',
                                     hdtk_decode=hdtk_decode,
                                     horizon=2,
                                     period_length=1)

NameError: name 'inventory' is not defined

In [20]:
fm.reset()

In [21]:
fm.areaselector.operate(1, 'harvest', 100.)

0.0

In [22]:
fm.compile_product(1, '1.')

100.0

In [23]:
fm.forestraster.allocate_schedule()

processing case 1 harvest ('tsa24_clipped', '1', '2401002', '204', '2401002') 155 34.0
dy 0
34 34.0 1.0 34.0
n 34 tarea 34.0
processing case 1 harvest ('tsa24_clipped', '1', '2401002', '204', '2401002') 153 9.0
dy 0
9 9.0 1.0 9.0
n 9 tarea 9.0
processing case 1 harvest ('tsa24_clipped', '1', '2401002', '204', '2401002') 145 3.0
dy 0
99 99.0 0.030303030303030304 3.0
n 3 tarea 3.0
processing case 1 harvest ('tsa24_clipped', '1', '2402002', '204', '2402002') 115 3.0
dy 0
3 3.0 1.0 3.0
n 3 tarea 3.0
processing case 1 harvest ('tsa24_clipped', '1', '2402002', '204', '2402002') 95 34.0
dy 0
34 34.0 1.0 34.0
n 34 tarea 34.0
processing case 1 harvest ('tsa24_clipped', '1', '2403000', '100', '2403000') 93 17.0
dy 0
17 17.0 1.0 17.0
n 17 tarea 17.0


In [52]:
src = rasterio.open('data/projected_harvest_2020.tif')
data = src.read()
#np.sum(data)
data.sum()

100

In [53]:
src.profile

{'driver': 'GTiff', 'dtype': 'uint8', 'nodata': 0.0, 'width': 41, 'height': 41, 'count': 1, 'crs': CRS.from_epsg(3005), 'transform': Affine(100.0, 0.0, 1112000.0,
       0.0, -100.0, 1124900.0), 'blockysize': 16, 'tiled': False, 'compress': 'lzw', 'interleave': 'band'}

In [25]:
data_init = rasterio.open('data/inventory_init.tif').read()
data_post = rasterio.open('data/inventory_2020.tif').read()

RasterioIOError: data/inventory_2020.tif: No such file or directory

In [26]:
data_init[1]

array([[  0,   0,   0, ...,   0,   0,   0],
       [ 95, 145,   0, ..., 145,  78,   0],
       [ 95, 145,   0, ...,  78,  78,   0],
       ...,
       [135, 135,   0, ...,   9,   9,   0],
       [135, 135, 135, ...,   9,   9,   0],
       [135, 135, 135, ...,   9,   9,   0]], dtype=uint32)

In [27]:
data_post[1]

array([[  0,   0,   0, ...,   0,   0,   0],
       [  1, 145,   0, ..., 145,  78,   0],
       [  1, 145,   0, ...,  78,  78,   0],
       ...,
       [135, 135,   0, ...,   9,   9,   0],
       [135, 135, 135, ...,   9,   9,   0],
       [135, 135, 135, ...,   9,   9,   0]], dtype=uint32)

In [28]:
data_diff = np.subtract(data_post[1], data_init[1], dtype='int64')

In [29]:
data_diff[data_diff < 0]

array([ -94,  -94,  -94,  -94,  -94,  -94,  -94,  -94,  -94,  -94,  -94,
        -94,  -94,  -94,  -94,  -94,  -92,  -92,  -92, -154,  -92,  -92,
        -92,  -92,  -92, -154, -154, -154,  -92,  -92,  -92,  -92,  -92,
        -92,  -92, -154, -154, -154, -154, -154, -154,  -92,  -92, -154,
       -154, -154, -154, -154, -154, -154, -154, -154, -154, -152, -114,
       -152, -114, -114, -152, -154, -154, -152, -152, -144, -152, -152,
       -154, -154, -154,  -94,  -94, -144, -152, -152, -154, -154, -154,
        -94,  -94,  -94, -154, -154, -154,  -94,  -94,  -94, -154, -154,
       -154,  -94,  -94,  -94,  -94,  -94,  -94,  -94, -144,  -94,  -94,
        -94])

In [75]:
data_diff.sum()

-12138

In [45]:
np.where(data_diff == -266176181)

(array([], dtype=int64), array([], dtype=int64))

In [128]:
np.where(data_diff == -154)

(array([21, 22, 22, 22, 23, 23, 23, 23, 23, 23]),
 array([19, 16, 17, 18, 16, 17, 18, 19, 20, 21]))

In [124]:
data_diff.shape

(3, 41, 41)

In [101]:
data_diff = data_post[1] - data_init[1]
data_diff[data_diff > 0]

array([], dtype=uint32)

In [98]:
data_init[1][data_init[1] > 0]

array([ 95, 145,  95, ...,   9,   9,   9], dtype=uint32)

In [99]:
data_post[1][data_post[1] > 0]

array([ 95, 145,  95, ...,   9,   9,   9], dtype=uint32)

In [100]:
np.iinfo(data_init[1].dtype)

iinfo(min=0, max=4294967295, dtype=uint32)

In [71]:
src.profile

{'driver': 'GTiff', 'dtype': 'uint8', 'nodata': 0.0, 'width': 41, 'height': 41, 'count': 1, 'crs': CRS.from_epsg(3005), 'transform': Affine(100.0, 0.0, 1112000.0,
       0.0, -100.0, 1124900.0), 'blockysize': 16, 'tiled': False, 'compress': 'lzw', 'interleave': 'band'}

In [59]:
fr = fm.forestraster
data = fr._snkd['harvest', 0]

In [63]:
np.sum(data)

0

In [29]:
fm.compile_actions()

In [30]:
dtk = ('tsa24_clipped', '1', '2401002', '204', '2401002')

In [31]:
dt = fm.dtypes[dtk]
dt.transitions

{('harvest',
  -1): [(('?', '?', '?', '?', '2421002'), 1.0, None, None, None, None, None)]}

In [12]:
fm.transitions

{'harvest': {('?',
   '?',
   '2402000',
   '?',
   '?'): {'': [(('?', '?', '?', '?', '2422000'),
     1.0,
     None,
     None,
     None,
     None,
     None)]},
  ('?',
   '?',
   '2403000',
   '?',
   '?'): {'': [(('?', '?', '?', '?', '2423000'),
     1.0,
     None,
     None,
     None,
     None,
     None)]},
  ('?',
   '?',
   '2403001',
   '?',
   '?'): {'': [(('?', '?', '?', '?', '2423001'),
     1.0,
     None,
     None,
     None,
     None,
     None)]},
  ('?',
   '?',
   '2401002',
   '?',
   '?'): {'': [(('?', '?', '?', '?', '2421002'),
     1.0,
     None,
     None,
     None,
     None,
     None)]},
  ('?',
   '?',
   '2402002',
   '?',
   '?'): {'': [(('?', '?', '?', '?', '2422002'),
     1.0,
     None,
     None,
     None,
     None,
     None)]},
  ('?',
   '?',
   '2403002',
   '?',
   '?'): {'': [(('?', '?', '?', '?', '2423002'),
     1.0,
     None,
     None,
     None,
     None,
     None)]},
  ('?',
   '?',
   '2402003',
   '?',
   '?'): {'': [(('?',

In [70]:
import rasterio
r = rasterio.open('data/projected_harvest_2021.tif')
data = r.read()

In [72]:
data

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]], dtype=uint8)

In [60]:
import rasterio
with rasterio.open('data/inventory_2020.tif') as dataset:
    data = dataset.read()
    profile = dataset.profile
mf = rasterio.MemoryFile()
with mf.open(**profile) as dataset:
    dataset.write(data)
foo = mf.open()



In [63]:
rasterio.open(mf)

<open DatasetReader name='/vsipythonfilelike/00dbd59a-a718-4bba-b20d-ef82e986c864/00dbd59a-a718-4bba-b20d-ef82e986c864' mode='r'>

In [56]:
def raster_memfile():
    import rasterio
    with rasterio.MemoryFile() as mf:
        with  mf.open('data/inventory_2020.tif', 'rw') as result:
            yield result
with raster_memfile() as foo:
    foo.shape

AttributeError: __enter__

In [16]:
import geopandas as gpd

In [47]:
#stands = gpd.read_file('ws3/examples/data/shp/tsa24_clipped.shp/stands.shp')
#stands = gpd.read_file('examples/data/shp/tsa24_clipped.shp/stands.shp')
#stands['theme4'] = stands.curve1
stands = gpd.read_file('examples/data/shp/tsa24_clipped/stands.shp')

In [48]:
stands.area.sum()

13667377.375751436

In [49]:
gstands = stands.groupby(theme_cols+['age'])

In [50]:
len(stands.theme4.unique())

9

In [51]:
for i, (name, group) in enumerate(gstands):
    dtk, age, area = tuple(map(lambda x: str(x), name[:-1])), int(name[-1]), group['area'].sum()
    print(i, dtk, age, area)

0 ('tsa24_clipped', '0', '2401000', '100', '2401000') 85 15.182274886309896
1 ('tsa24_clipped', '0', '2401000', '100', '2401000') 95 20.653788842921458
2 ('tsa24_clipped', '0', '2401000', '100', '2401000') 105 1.109374490200082
3 ('tsa24_clipped', '0', '2401000', '100', '2401000') 125 25.73174833461312
4 ('tsa24_clipped', '0', '2401000', '100', '2401000') 135 62.02382759721078
5 ('tsa24_clipped', '0', '2401000', '100', '2401000') 145 45.32228954967691
6 ('tsa24_clipped', '0', '2401000', '100', '2401000') 155 3.052804424896181
7 ('tsa24_clipped', '0', '2402005', '1201', '2402005') 85 1.812979326195168
8 ('tsa24_clipped', '1', '2401002', '204', '2401002') 78 103.76740323520823
9 ('tsa24_clipped', '1', '2401002', '204', '2401002') 80 4.173147018452507
10 ('tsa24_clipped', '1', '2401002', '204', '2401002') 85 282.1296355046733
11 ('tsa24_clipped', '1', '2401002', '204', '2401002') 91 73.1021561503533
12 ('tsa24_clipped', '1', '2401002', '204', '2401002') 93 28.37956666951611
13 ('tsa24_cli

In [23]:
gdf.area.sum()

13667377.375751436

In [24]:
gdf.shape

(190, 10)

In [39]:
import ws3.forest, ws3.common
from spadesws3 import import_inventory, update_areas
theme_cols = ['theme0', 'theme1', 'theme2', 'theme3']
model_name='tsa24_clipped'
model_path='examples/data/woodstock_model_files'
base_year=2020
shp_path='examples/data/shp/tsa24_clipped/stands.shp'
tif_path='data/inventory_2020.tif'
horizon=2
period_length=10
theme_cols=theme_cols
max_age=999
pixel_area=1.
fm = ws3.forest.ForestModel(model_name=model_name,
                            model_path=model_path,
                            base_year=base_year,
                            horizon=horizon,
                            period_length=period_length,
                            max_age=max_age)
fm.import_landscape_section()
inventory = import_inventory(shp_path, tif_path, theme_cols=theme_cols)
update_areas(fm=fm, 
             age_raster=inventory['raster_data'][1], 
             hdtk_raster=inventory['raster_data'][0], 
             hdtk_decode=inventory['hdtk_decode'], 
             pixel_area=pixel_area)

In [44]:
fr = ws3.spatial.ForestRaster(hdt_map=inventory['hdtk_decode'],
                                hdt_func=hdt_func,
                                src_path=mf,
                                snk_path=snk_path,
                                acode_map=acode_map,
                                forestmodel=fm,
                                base_year=fm.base_year, # to do: tweak ForestRaster constructor to skip this (read from fm)
                                horizon=fm.horizon, # to do: tweak ForestRaster constructor to skip this (read from fm)
                                period_length=fm.period_length, # to do: tweak ForestRaster constructor to skip this (read from fm)
                                time_step=1)


NameError: name 'hdt_func' is not defined

In [43]:
import ws3.spatial

In [42]:
pip install profilehooks

Note: you may need to restart the kernel to use updated packages.


In [11]:
fm

In [12]:
fm._themes

[{'__name__': 'theme0',
  '__description__': '',
  'tsa24_clipped': 'tsa24_clipped'},
 {'__name__': 'theme1', '__description__': '', '0': '0', '1': '1'},
 {'__name__': 'theme2',
  '__description__': '',
  '2402002': '2402002',
  '2401007': '2401007',
  '2402001': '2402001',
  '2401005': '2401005',
  '2402000': '2402000',
  '2403004': '2403004',
  '2403006': '2403006',
  '2401004': '2401004',
  '2401006': '2401006',
  '2402004': '2402004',
  '2402007': '2402007',
  '2403005': '2403005',
  '2401002': '2401002',
  '2403007': '2403007',
  '2403003': '2403003',
  '2401000': '2401000',
  '2402005': '2402005',
  '2402006': '2402006',
  '2401003': '2401003',
  '2403002': '2403002',
  '2402003': '2402003',
  '2403000': '2403000',
  '2401001': '2401001',
  '2403001': '2403001'},
 {'__name__': 'theme3',
  '__description__': '',
  '304': '304',
  '100': '100',
  '1201': '1201',
  '204': '204',
  '104': '104'},
 {'__name__': 'theme4',
  '__description__': '',
  '2402002': '2402002',
  '2401007': '2

In [23]:
import geopandas as gpd

gdf = gpd.read_file('examples/data/shp/tsa24_clipped/stands.shp')

In [24]:
gdf

theme0  theme1   theme2   curve1   curve2 SPECIES_CD  age  \
0    tsa24_clipped       1  2401002  2401002  2401002        PLI  145   
1    tsa24_clipped       1  2401002  2401002  2401002        PLI  145   
2    tsa24_clipped       1  2401002  2401002  2401002        PLI  135   
3    tsa24_clipped       1  2402002  2402002  2402002        PLI   93   
4    tsa24_clipped       1  2401000  2401000  2401000         SX  145   
..             ...     ...      ...      ...      ...        ...  ...   
185  tsa24_clipped       1  2401002  2401002  2401002        PLI   85   
186  tsa24_clipped       1  2401002  2401002  2401002        PLI   85   
187  tsa24_clipped       1  2401002  2401002  2401002        PLI   95   
188  tsa24_clipped       0  2401000  2401000  2401000         SB   95   
189  tsa24_clipped       1  2402002  2402002  2402002        PLI   95   

          area  theme3   theme4  \
0     0.111814     204  2401002   
1     0.113925     204  2401002   
2     7.025088     204  2401002   
3    11.029940     204  2402002   
4     9.581284     100  2401000   
..         ...     ...      ...   
185   5.667730     204  2401002   
186   1.811041     204  2401002   
187   1.137586     204  2401002   
188   0.494253     100  2401000   
189   0.387243     204  2402002   

                                              geometry  
0    MULTIPOLYGON (((1112711.004 1120816.405, 11127...  
1    POLYGON ((1113299.500 1120834.770, 1113298.336...  
2    POLYGON ((1112035.066 1121064.403, 1112071.399...  
3    POLYGON ((1114394.740 1120822.943, 1114394.421...  
4    MULTIPOLYGON (((1114322.804 1120983.973, 11143...  
..                                                 ...  
185  POLYGON ((1115036.356 1124809.762, 1115037.888...  
186  POLYGON ((1114157.650 1124633.924, 1114154.478...  
187  POLYGON ((1114675.233 1124802.103, 1114684.360...  
188  POLYGON ((1114249.328 1124669.031, 1114271.225...  
189  POLYGON ((1112837.042 1124802.518, 1112821.020...  

[190 rows x 11 columns]

In [21]:
gdf['theme4'] = gdf.curve1

In [22]:
gdf.to_file('examples/data/shp/tsa24_clipped/stands.shp')

In [17]:
pip install geopandas

Note: you may need to restart the kernel to use updated packages.


In [19]:
open('foo')

FileNotFoundError: [Errno 2] No such file or directory: 'foo'